package ru.ivansteklow.tf2mod;

import java.util.ArrayList;

import org.apache.logging.log4j.Logger;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.relauncher.Side;
import ru.ivansteklow.tf2mod.config.ModConfig;
import ru.ivansteklow.tf2mod.init.CraftTweaker;
import ru.ivansteklow.tf2mod.init.References;
import ru.ivansteklow.tf2mod.network.ModNetworkWrapper;
import ru.ivansteklow.tf2mod.network.PacketMetalRefinery;
import ru.ivansteklow.tf2mod.proxy.ServerProxy;

@Mod(modid = References.MODID, name = References.NAME, version = References.VERSION, acceptedMinecraftVersions = References.ACCEPTED_VERSIONS, dependencies = References.MOD_DEPENDENCIES)
public class Core {

	@Instance
	public static Core instance;

	@SidedProxy(clientSide = References.CLIENT_PROXY_CLASS, serverSide = References.SERVER_PROXY_CLASS)
	public static ServerProxy proxy;

	public static Logger logger;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		logger = event.getModLog();
		logger.info("Initializing TeamFortress2 Modification for Minecraft 1.12.2");
		setupModInfo(event.getModMetadata());
		ModConfig.preInit();
		proxy.preInit(event);
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		CraftTweaker.init();
		proxy.Init(event);
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		proxy.postInit(event);
	}

	public void setupModInfo(ModMetadata meta) {
		meta.autogenerated = false;
		meta.modId = References.MODID;
		meta.name = References.NAME;
		meta.version = References.VERSION;
		meta.description = References.DESCRIPTION;
		meta.credits = References.CREDITS;
		meta.updateJSON = References.UPDATE_JSON;
		ArrayList<String> authors = new ArrayList<String>();
		authors.add("IvanSteklow");
		meta.authorList = authors;
	}

	@EventHandler
	private void serverStarting(FMLServerStartingEvent event) {
		ModNetworkWrapper.INSTANCE.registerMessage(PacketMetalRefinery.PacketMetalRefineryHandler.class, PacketMetalRefinery.class, 0,
				Side.SERVER);
	}

}